#!/bin/bash
set -e
function run_build_for {
  if [ ! -f ./$1/$SPECS_HAVE_RUN_FILE ]; then # don't rerun specs that have already run
    if [ -d ./$1 ]; then
      echo "Running specs for $1"
      pushd ./$1
      bundle install --binstubs --standalone --without documentation --path ../bundle
      script/run_build
      popd
    else
      echo ""
      echo "WARNING: The ./$1 directory does not exist. Usually the"
      echo "travis build cds into that directory and run the specs to"
      echo "ensure the specs still pass with your latest changes, but"
      echo "we are going to skip that step."
      echo ""
    fi;
  fi;
}
run_build_for "rspec-core"
run_build_for "rspec-expectations"
run_build_for "rspec-mocks"
run_build_for "rspec-support"
